name: vendor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.3.0
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  # a package containing annotations for freezed.
  freezed_annotation: ^2.2.0
  go_router: ^13.0.0
  google_maps_flutter: ^2.5.0
  hooks_riverpod: ^2.4.9
  intl: ^0.18.1
  # Generating code for JSON serialization and deserialization.
  json_annotation: ^4.8.1
  location: ^5.0.3
  otp_text_field: ^1.1.3
  path_provider: ^2.1.1
  phone_form_field: ^8.1.1
  readmore: ^2.2.0
  riverpod_annotation: ^2.3.3
  timeago: ^3.6.0
  # A package for mapping data models automatically.
  auto_mappr: ^2.1.1
  # Dependency Injection service locator
  injectable: ^2.3.0
  # Dependency Injection service locator
  get_it: ^7.6.0
  #Flutter plugin for reading and writing simple key-value pairs
  shared_preferences: ^2.2.2
  #Flutter widgets for easily adding gaps inside Flex widgets such as Columns and Rows or scrolling views.
  gap: ^3.0.1
  #Flutter plugin for picking images from the device
  image_picker: ^1.0.6
  # A toast library for friendly user interfaces message
  fluttertoast: ^8.2.4
  #Flutter plugin for accessing device contacts
  flutter_contacts: ^1.1.7+1
  # Validators for form fields
  form_builder_validators: ^9.1.0
  # Form builder creation of data collection forms in Flutter by removing the boilerplate needed to build a form, validate fields, react to changes and collect final user input.
  flutter_form_builder: ^9.1.1
  equatable: ^2.0.5
  easy_date_timeline: ^1.0.2
  # Provides charting capabilities for your Flutter app.
  syncfusion_flutter_charts: 22.2.11
  #for launching a URL and Intent
  url_launcher: ^6.2.3
  url_launcher_platform_interface: ^2.2.0
  url_launcher_android: ^6.2.2
  url_launcher_ios: ^6.2.4
  flutter_timezone: ^1.0.8
  intl_phone_field: ^3.2.0

dev_dependencies:
  # Build Runner is a package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
  # Use the below command to generate files:
  # `dart run build_runner build --delete-conflicting-outputs`
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  # used for code generation related to assets,
  flutter_gen_runner: ^5.3.1
  # Injectable Generator is a generator for injectable.
  injectable_generator: ^2.4.0
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  # Important: Used to generate localization manually in case it's not generated automatically
  auto_mappr_annotation: ^2.1.0
  # `dart run intl_utils:generate`
  intl_utils: ^2.8.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
flutter_gen:
  output: lib/core/gen/
  line_length: 50

  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/imgs/onboarding/
    - assets/svg/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
          style: normal

        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
          style: normal
flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
  class_name: AppLocalization
  main_locale: en
  synthetic-package: false
